name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup System
      run: |
        sudo apt-get -qq update
        sudo apt-get install -y libgdbm-dev libgdbm5        
    - name: make
      run: make
